---
# Handlers for the_bastion role

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  listen: restart sshd

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart bastion services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - ssh
  listen: restart bastion services

- name: Restart osh-sync-watcher
  ansible.builtin.systemd:
    name: osh-sync-watcher
    state: restarted
  listen: restart osh-sync-watcher
