---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: podman

platforms:
  - name: debian13-bastion-new-tarball
    image: docker.io/geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    userns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - new_install
      - install_tarball

  - name: debian13-bastion-new-git
    image: docker.io/geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    userns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - new_install
      - install_git

  # we need to use debian12 for upgrade testing, as debian13 isn't supported by bastion v3.20.00
  - name: debian12-bastion-upgrade-tarball
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    userns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - upgrade_test
      - install_tarball

    # we need to use debian12 for upgrade testing, as debian13 isn't supported by bastion v3.20.00
  - name: debian12-bastion-upgrade-git
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    userns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - upgrade_test
      - install_git

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        bastion_install_syslog_ng: true
        bastion_encrypt_home: false
        bastion_backup_dir: /root/backups
        bastion_upgrade_backup_before: true
        bastion_plugin_mfa_config:
          - name: selfAddIngressKey
            mfa: true
          - name: groupInfo
            mfa: false
          - name: accountCreate
        bastion_remote_syslog_enabled: true
        bastion_remote_syslog_host: "127.0.0.1"
        bastion_remote_syslog_port: 514
        bastion_remote_syslog_protocol: "udp"
      install_tarball:
        bastion_install_method: tarball
      install_git:
        bastion_install_method: git
      new_install:
        bastion_first_admin:
          username: bastionadmin
          ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICFSs/v2JZSdhMDJYd2wxmvGI5x86exT7YmGENx+q+XR example@adfinis"
      upgrade_test:
        bastion_first_admin:
          username: bastionadmin
          # bastion v3.20.00 doesn't support ed25519 keys, support has been added in v3.21.00
          ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChX66tWFWbj5OVv4T/z9PrExfznMbDSQ/hQXFyGvYEll2DZWDvqlWc+h1epRdWcDji7yK8BzDxL52R4m8TrFYcSWBUnH6jhmlt1t/Sup4RB4MlTE7KK+kO5zr1ipyQt5IEULzbzBZgkkI4yWX8GoYle6uHEEKy4vqxcqTm28Y54BGppVLS4JGlffGMUTLaEJQeZ+d8DDy/39JQBKzOLck2MkmzsdPWNIxowagnBwONCrhEVamW/9fdMI1F0xim+EiLKHtXmaYo2sms7uo9LpvlnkHTE4XNiokqDLDA6+g1Bb1toa2nxLrZu2WjP1KzhdsQ8zJAObkheeUc/GLb7hle7lCCUfrcvSx0pAEj1Qf1rjVDdtu11NVUKNIEPF3c92J0JusZ1H03n1+h/YU41zFBJi7Y3w+4Av2dykzbxSiYzYdFLpXAj7lbEp2BESent42p1bJ0n3PTOxnjnCNxgQapJUBN+lmSQ1aynQZOFdEpkFg7mlQ/JomW7lD5FJwQjH0= example@adfinis"  # noqa: yaml[line-length]

verifier:
  name: ansible
