---
- name: Example Playbook to Install The Bastion
  hosts: bastion_servers
  become: true
  vars:
    bastion_first_admin:
      username: "bastionadmin"
      ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NT... admin@company.com"

    # Basic configuration
    bastion_install_syslog_ng: true
    bastion_new_install: true

    # Optional: Enable home directory encryption
    # bastion_encrypt_home: true
    # bastion_encryption_passphrase: !vault |
    #   $ANSIBLE_VAULT;1.1;AES256
    #   ...

    # Optional: Install additional tools
    # bastion_install_yubico_piv_checker: true
    # bastion_install_mkhash_helper: true

    # Optional: Custom bastion configuration
    # bastion_config:
    #   bastionName: "sensfortress"
    #   adminAccounts: "bastionadmin,otheradmin"
    #   superOwnerAccounts: "superadmin"
    #   defaultAccountTTL: "90"

  roles:
    - adfinis.the_bastion

  post_tasks:
    - name: Display connection information
      ansible.builtin.debug:
        msg:
          - The Bastion has been successfully installed!
          - ""
          - "Connect to your bastion using:"
          - "ssh {{ bastion_first_admin.username }}@{{ ansible_default_ipv4.address | default(ansible_host) }}"
          - ""
          - "For more information, visit: https://ovh.github.io/the-bastion/"
