---
- name: Example Playbook to Install The Bastion with GPG Support
  hosts: bastion_servers
  become: true
  vars:
    bastion_first_admin:
      username: "bastionadmin"
      ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NT... admin@company.com"

    # Basic configuration
    bastion_install_syslog_ng: true

    # Enable GPG encryption and signature
    bastion_gpg_enabled: true
    bastion_gpg_key_generate: true

    # Option 1: Import an existing admin GPG public key
    bastion_admin_gpg_key_import: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      
      mQENBGH8...
      [Your Admin GPG Public Key Here]
      ...
      -----END PGP PUBLIC KEY BLOCK-----

    # Option 2: Generate admin GPG key (for testing - not recommended in production)
    # bastion_admin_gpg_key_generate: true
    # bastion_admin_gpg_key_name: "Bastion Admin"
    # bastion_admin_gpg_key_email: "admin@company.com"
    # bastion_admin_gpg_key_type: "ed25519"  # or "rsa4096"
    # bastion_admin_gpg_key_passphrase: !vault |
    #   $ANSIBLE_VAULT;1.1;AES256
    #   ...

    # Optional: Enable home directory encryption
    # bastion_encrypt_home: true
    # bastion_encryption_passphrase: !vault |
    #   $ANSIBLE_VAULT;1.1;AES256
    #   ...

  pre_tasks:
    - name: Ensure Python pexpect is installed
      ansible.builtin.package:
        name: python3-pexpect
        state: present

    - name: Ensure GnuPG is installed
      ansible.builtin.package:
        name: gnupg
        state: present

  roles:
    - adfinis.the_bastion

  post_tasks:
    - name: Display connection information
      ansible.builtin.debug:
        msg:
          - The Bastion has been successfully installed with GPG support!
          - ""
          - "Connect to your bastion using:"
          - "ssh {{ bastion_first_admin.username }}@{{ ansible_default_ipv4.address | default(ansible_host) }}"
          - ""
          - "GPG features enabled:"
          - "- TTY recordings will be signed with the bastion GPG key"
          - "- Backups will be encrypted with the admin GPG key"
          - "- Test the configuration: /opt/bastion/bin/cron/osh-encrypt-rsync.pl --config-test"
          - ""
          - "For more information, visit: https://ovh.github.io/the-bastion/"
