---
- name: Converge - HA Master Setup
  hosts: ha_master,ha_slave
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600

    - name: Install Python expect module
      ansible.builtin.package:
        name: python3-pexpect
        state: present

  roles:
    - role: adfinis.the_bastion
