---
name: Delete role from Ansible Galaxy

# configure manual trigger
on:
  workflow_dispatch:

permissions: {}

jobs:
  delete:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-galaxy-DELETE-role.yaml@e64e43cab282caa112c5fa5df4d43fd82ed8711f # v0.9.0
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
