---
name: Delete role from Ansible Galaxy

# configure manual trigger
on:
  workflow_dispatch:

permissions: {}

jobs:
  delete:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-galaxy-DELETE-role.yaml@e5f6f4f45de85bb92d71713f9c539abf424528ac # v0.10.1
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
