---
name: Delete role from Ansible Galaxy

# configure manual trigger
on:
  workflow_dispatch:

permissions: {}

jobs:
  delete:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-galaxy-DELETE-role.yaml@7b2184d76870cc7c281d081a6ebabc15264dcc1f # v0.10.0
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
