---
# runs on each push to main and is responsible for creating new tags/releases
name: Create Semantic Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  semantic-release:
    uses: adfinis/github-workflows-bareos/.github/workflows/semantic-release.yaml@eedff15b52be3c117bd5f7a28492494596399311 # v0.8.0
    secrets:
      ADFINISBOT_GITHUB_TOKEN: ${{ secrets.ADFINISBOT_GITHUB_TOKEN }}
